# General Params
verbosity: 3
use_threadsafe_submap_collection: true
use_transform_caching: true
transform_lookup_time: 0.1
global_frame_name: &global_frame_name map
visualization_interval: -1.0
data_logging_interval: -1.0
print_timing_interval: 0.0
max_input_queue_length: 20
ros_spinning_threads: 8
depth_type: 16U
color_msg_type: rgb8
use_saved_embeddings: true

labels:
  type: mini_csv
  file_name: /home/xiangweizeng/3D_slam/sematic-mapping/panoptic_mapping_ws/src/panoptic_mapping/panoptic_mapping_ros/config/classes/realsense_labels_mini.csv
camera:
  verbosity: 1
  width: 640  # Px
  height: 480
  vx: 322.398
  vy: 240.039
  fx: 387.449
  fy: 386.943
  max_range: 2.0  # m
  min_range: 0.5
  
submap_allocator:
  type: semantic  # semantic
  verbosity: 1   
  
  # submaps
  voxels_per_side: &voxels_per_side 16
  truncation_distance: -2 # negative = #vs
  use_class_layer: true
  frame_id: *global_frame_name
  max_embedding_weight: 1000.0
  min_embedding_weight: 0.00001
  mesh:
    clear_foreign_voxels: true
    required_belonging_corners: &required_belonging_corners 4
  classification:
    type: moving_binary_count
  
  # Semantic
  small_instance_voxel_size: 0.02
  medium_instance_voxel_size: 0.03
  large_instance_voxel_size: 0.04
  background_voxel_size: 0.1
  unknown_voxel_size: 0.05
  
freespace_allocator:
  type: monolithic  # monolithic
  verbosity: 1  
  voxels_per_side: *voxels_per_side 
  truncation_distance: -2   
  voxel_size: 0.3

id_tracker:
  type: detectron # ground_truth, projective, detectron, single_tsdf
  verbosity: 3
  whitelist_classes: toy,doll,vegetable,vegetable toy,vegetable doll,chilli doll,bitter gourd doll,eggplant doll    
  
  # Projective ID tracker
  depth_tolerance: -2  # m, negative = #vs
  tracking_metric: IoU  # IoU, overlap
  match_acceptance_threshold: 0.2 
  min_allocation_size: 300 # px, for submap allocation.
  use_class_data_for_matching: true

tsdf_integrator:  
  type: class_projective # projective, class_projective, single_tsdf
  verbosity: 1     

  # Projective
  use_weight_dropoff: true
  max_weight: 10000
  interpolation_method: adaptive  # nearest, bilinear, adaptive
  foreign_rays_clear: true
  integration_threads: 8
  allocate_neighboring_blocks: false
  
  # Class Projective
  use_binary_classification: true
  use_instance_classification: &use_instance_classification true
  update_only_tracked_submaps: false
  
map_management:
  type: submaps
  verbosity: 4
  
  # Frequencies
  prune_active_blocks_frequency: 1 
  activity_management_frequency: 1
  change_detection_frequency: 1
  
  # Behavior
  merge_deactivated_submaps_if_possible: true
  apply_class_layer_when_deactivating_submaps: true
  detect_disappear_by_sensor_data: true
  remove_absent_submaps: true
  
  activity_manager:
    required_reobservations: 5 # Consecutive observations to keep new submaps.
    deactivate_after_missed_detections: 5  # Deactivate submaps when not observed for x frames.
  
  tsdf_registrator:
    verbosity: 3
    min_voxel_weight: 0.000001
    error_threshold: -2 # m, negative = #vs
    match_rejection_points: 20  
    match_rejection_percentage: 0.02
    match_acceptance_points: 20
    match_acceptance_percentage: 0.5
    normalize_by_voxel_weight: false
  
  change_detector:
    verbosity: 3
    strong_disappear_threshold: -10 # m, negative = #vs
    weak_disappear_threshold: -2 # m, negative = #vs
    match_strong_disappear_points: 50
    match_strong_disappear_percentage: 0.3
    match_weak_disappear_points: 50
    match_weak_disappear_percentage: 0.6
    match_weak_average_distance: -4 # m, negative = #vs
    detection_threads: 1
    use_classification_for_tiny: true
    min_isolated_points_size: 3000
    classification_only_background: false
    classification_use_no_class: true
    limit_range: true
    classification_disappear_frames_threshold: 3
    classification_disappear_threshold: 0.01 # m, negative = #vs
    classification_disappear_percentage: 0.5
    classification_disappear_average_distance: -1 # m, negative = #vs
    classification_projected_percentage: 0.9
    
  layer_manipulator:
      verbosity: 3
      use_instance_classification: *use_instance_classification
      required_belonging_corners: *required_belonging_corners
  
visualization:  
  submaps:
    type: submaps  # submaps, single_tsdf
    verbosity: 1
    color_mode: instances # submaps, instances, color, normals, classes, change, classification
    visualization_mode: all  # all, active, active_only, inactive, persistent
    visualize_other_mode: false
    submap_color_discretization: 20
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_free_space: true
    visualize_bounding_volumes: true
    include_free_space: false
    mesh_min_weight: 0.000001
    class_type_to_pub_for_occ: toy,doll,vegetable toy,vegetable doll
  
  planning:
    verbosity: 1
    visualize_slice: true
    slice_resolution: 0.1
    slice_height: -0.5
  
  tracking:
    verbosity: 1
    visualize_tracking: true

  changed_submaps:
    verbosity: 5
    change_point_threshold: 10
    only_use_aabb: false
    box_only_align_z: true
    min_obb_length: 0.02
    obb_frame_id: map
    use_redetection_for_add: true
    use_space_unique_boxes: true
    box_overlap_threshold: 0.5
