int32 image_id
sensor_msgs/Image rgb_image
string labels
string query_description
panoptic_mapping_msgs/VllmProcessingMode mode
---
int32 image_id
bool success
BoxInfo[] bounding_boxes
BoxRelationship[] relationships